version: '3.0'

# https://hub.docker.com/r/apache/nifi
# Wait about 1 minute and try login: (accept certificate)
# https://localhost:8443/nifi/
# login/password: admin/123456789012


services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456789012
      - NIFI_WEB_HTTP_HOST=localhost # if deloyed on remote IP, change with public IP
      - NIFI_WEB_PROXY_HOST=localhost:8443 # same here
