version: '3.0'

# https://hub.docker.com/r/apache/nifi
# Wait about 1 minute and try login:
# https://localhost:8443/nifi/
# login/password: admin/123456789012


services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456789012

