version: '3.5'

services:
  jupiter-spark:
    build:
      context: ./
    container_name: jupyter-spark
    volumes:
      - ./notebooks/:/home/jovyan/:rw
      - ./spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf:rw
    ports:
      - "8888:8888"
      - "4040:4040"
    stdin_open: true
    tty: true
    hostname: localhost
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
#      JUPYTER_RUNTIME_DIR: "/tmp"   # uncomment if problems with kernel start on Windows
    user: root


