version: '3.5'

services:
  jupiter-spark:
    build:
      context: ./
    container_name: jupyter-spark
    volumes:
      - ./notebooks/:/home/jovyan/:rw
    ports:
      - "8888:8888"
      - "4040:4040"
    stdin_open: true
    tty: true
    hostname: localhost
    environment:
      GRANT_SUDO: "yes"
    user: root


