# Add this to your /etc/hosts (linux) or C:\Windows\System32\drivers\etc\hosts:
#  127.0.0.1 kafka
#  127.0.0.1 schema-registry

version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:3.4.13
    container_name: zookeeper 
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:2.1.0
    container_name: kafka 
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_BROKER_ID: '0'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_NUM_PARTITIONS: '12'
      KAFKA_COMPRESSION_TYPE: 'gzip'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: '9091'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      restart: always
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.1
    container_name: schema_registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"

  #  http://localhost:8090/ui
  akhq:
    image: tchiotludo/akhq:0.20.0
    container_name: akhq 
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"

              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - "8090:8080"
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - schema-registry